name: Publish Retype powered website to GitHub Pages
on:
  workflow_dispatch:
  push:
    branches:
      - source

jobs:
  publish:
    permissions:
      contents: write
    name: Publish to main branch
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: retypeapp/action-build@latest
      - uses: DoidoTeam/action-github-pages@e78fdc953cc06e39f8e2318a9a01cb40497e7223
        with:
          branch: main
          update-branch: true