name: Publish Retype powered website to GitHub Pages
on:
  workflow_dispatch:
  push:
    branches:
      - source

jobs:
  publish:
    permissions:
      contents: write
    name: Publish to main branch
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: retypeapp/action-build@latest
      - uses: DoidoTeam/action-github-pages@d8d5017fecda7da08b8c9de5545aa801d8b8e7e2
        with:
          branch: main
          update-branch: true